[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "fridge"
name = "half and half"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "fridge"
name = "chili crisp"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "fridge"
name = "butter"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "fridge"
name = "cherry tomatoes"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "fridge"
name = "miso paste"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "fridge"
name = "gochujang"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "fridge"
name = "shredded cheese"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "fridge"
name = "parmesan cheese"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "fridge"
name = "monterey jack cheese"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "fridge"
name = "sharp white cheddar cheese"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "fridge"
name = "Stubb's bbq sauce"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "fridge"
name = "worcestershire sauce"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "fridge"
name = "hoisin sauce"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "fridge"
name = "soy sauce"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "fridge"
name = "pesto"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "fridge"
name = "sour cream"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "fridge"
name = "cottage cheese"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "fridge"
name = "homemade chicken stock"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "freezer"
name = "shrimp"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "freezer"
quantity = "6 thighs"
name = "skin-on boneless chicken thighs"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "freezer"
name = "frozen fruit mix (strawberries, cherries, pomegranate, blueberries)"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "freezer"
name = "frozen fruit mix (raspberries, blackberries, blueberries)"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "freezer"
name = "chow mein stir fry mix"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "freezer"
name = "spring vegetable mix"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "freezer"
name = "cheesy jalapeño loaded chicken nuggets"

