[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "fridge"
name = "half and half"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "fridge"
name = "chili crisp"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "fridge"
name = "butter"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "fridge"
name = "cherry tomatoes"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "fridge"
name = "miso paste"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "fridge"
name = "gochujang"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "fridge"
name = "shredded cheese"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "fridge"
name = "parmesan cheese"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "fridge"
name = "monterey jack cheese"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "fridge"
name = "sharp white cheddar cheese"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "fridge"
name = "Stubb's bbq sauce"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "fridge"
name = "worcestershire sauce"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "fridge"
name = "hoisin sauce"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "fridge"
name = "soy sauce"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "fridge"
name = "pesto"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "fridge"
name = "sour cream"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "fridge"
name = "cottage cheese"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "fridge"
name = "homemade chicken stock"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "freezer"
name = "shrimp"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "freezer"
quantity = "6 thighs"
name = "skin-on boneless chicken thighs"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "freezer"
name = "frozen fruit mix (strawberries, cherries, pomegranate, blueberries)"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "freezer"
name = "frozen fruit mix (raspberries, blackberries, blueberries)"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "freezer"
name = "chow mein stir fry mix"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "freezer"
name = "spring vegetable mix"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "freezer"
name = "cheesy jalapeño loaded chicken nuggets"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "spices"
name = "garlic powder"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "spices"
name = "onion powder"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "spices"
name = "MSG"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "spices"
name = "salt"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "spices"
name = "Tajín"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "spices"
name = "bay leaves"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "spices"
name = "saffron"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "spices"
name = "Tony Chachere's creole seasoning"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "spices"
name = "crushed red pepper"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "spices"
name = "ground ginger"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "spices"
name = "ground cumin"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "spices"
name = "ground nutmeg"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "spices"
name = "Italian seasoning"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "spices"
name = "dried basil leaves"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "spices"
name = "mustard powder"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "spices"
name = "garam masala"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "spices"
name = "liquid hickory smoke"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "spices"
name = "dried oregano leaves"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "spices"
name = "dried thyme"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "spices"
name = "ground turmeric"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "spices"
name = "tikka masala powder"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "spices"
name = "rubbed sage"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "spices"
name = "ground coriander"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "spices"
name = "ancho chile powder"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "spices"
name = "celery salt"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "spices"
name = "dark chili powder"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "pantry"
name = "5 minute grits"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "pantry"
name = "golden curry - medium hot"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "pantry"
name = "olive oil"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "pantry"
name = "peanut oil"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "pantry"
name = "peanut butter with honey"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "pantry"
name = "canned tuna"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "pantry"
name = "canned chickpeas"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "pantry"
name = "Tapatío"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "pantry"
name = "furikake"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "pantry"
name = "panko"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "pantry"
name = "Quaker granola"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "pantry"
name = "brown gravy mix"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "pantry"
name = "Rao's Alfredo sauce"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "pantry"
name = "Knorr chicken bouillon powder"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "pantry"
name = "Kewpie mayo"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "pantry"
name = "aji-mirin"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "pantry"
name = "rice vinegar"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "pantry"
name = "Sapporo Ichiban ramen"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "pantry"
name = "Myojo udon noodles"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "pantry"
name = "lasagna noodles"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "pantry"
name = "apple cider vinegar"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "pantry"
name = "distilled white vinegar"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "pantry"
name = "red wine vinegar"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "pantry"
name = "Korean ramen toppings (seafood)"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "pantry"
name = "arborio rice"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "pantry"
name = "enriched long grain rice"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "pantry"
name = "AP flour"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "pantry"
name = "corn starch"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "pantry"
name = "baking powder"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "pantry"
name = "dark brown sugar"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "pantry"
name = "granulated sugar"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "pantry"
name = "potato starch"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "pantry"
name = "extra thin rice paper"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "pantry"
quantity = "1 lb"
name = "dried pinto beans"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "pantry"
quantity = "1 lb"
name = "dried black beans"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "pantry"
name = "half loaf sourdough bread"

[[items]]
added_at = "2026-06-19"
last_verified_at = "2026-06-19"
category = "pantry"
name = "fajita tortillas"

